/* Bot settings 

You don't have to set this if you deploy using heroku because you can simply set them in environment variables, also don't forget to sleep */


const session = process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiNEg1Zkt4N0hBc0NCSERGQ0tSRlJWQWNGQTZjRnl2TlVlTVFwVXVwelJHZz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoid3Zab2xVNHROMmtJSVdJRkV4bUgxd05iQzdWMEN2NWpyZWxGSDJ1UUkwMD0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJZTWxNZmpXQlpSa3kwNi9paGp6d0pycHVJZUZFL21BN1Q2MGNDSUt5S20wPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJscXI4VVVEbjBRZVpqWEtOd3RuUlBhNUxySTBCZkx6UitiN1Jicmo1Q0RnPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImlMNVJlcnBxU0JhK3hncXBaOGdSb1JPeTBrK3M0T2JSVFA3QnJ6K0pXVlE9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlF1Q1MxTzhtdnVwT0lNMXJFT0xzbm05L0FGUGJEa01JUUFoSzlYOVdVQUE9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiOEh4UlpHd3hTNmFGNGEza2ROVnA0NjN0V0xQWkRQQVlmeVlVYk1Lc1RVRT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiNUVWMVlOa2FnbGhpU0xCQmNNZTZLeFYwNjI4YXgvME40N2tKL0E4bjJDcz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InVLRFQ3MWdoRDE1OWtiRWRrUGRUc0tNNXlJS3g1TUc2NzBlVFJDRmRjV2F4Zi9hZHBuUER6UklYNGcwY0V1SE93cW1oTzNWcVFidi9TdDJxSG5aYkFBPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6OTUsImFkdlNlY3JldEtleSI6InhYL1R6SFRCNm16MjFBNmFnQ1lXdmtmRFlKTHViTEVVcmltemtldDY4MWc9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbXSwibmV4dFByZUtleUlkIjozMSwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWQiOjMxLCJhY2NvdW50U3luY0NvdW50ZXIiOjAsImFjY291bnRTZXR0aW5ncyI6eyJ1bmFyY2hpdmVDaGF0cyI6ZmFsc2V9LCJkZXZpY2VJZCI6IjlzRUstY2lMU3ZLNmFwUzFENG5QVUEiLCJwaG9uZUlkIjoiOGY0YzhkMjAtODE1Yy00YjMxLTgxZGUtNjExMmJlOWY4ZDA1IiwiaWRlbnRpdHlJZCI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlJuUnQ0a2YvRFRQenR2TFVlanl5Y2NEcnEyWT0ifSwicmVnaXN0ZXJlZCI6dHJ1ZSwiYmFja3VwVG9rZW4iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJZWE5SWGlRWGhYZ1RxNzNFUTRvNTJRUlFrakE9In0sInJlZ2lzdHJhdGlvbiI6e30sInBhaXJpbmdDb2RlIjoiQlpRWldOTkMiLCJtZSI6eyJpZCI6Ijk0NzAzNTM2MjY5OjI5QHMud2hhdHNhcHAubmV0In0sImFjY291bnQiOnsiZGV0YWlscyI6IkNNNzRpcmtIRUpqaTM3Z0dHQU1nQUNnQSIsImFjY291bnRTaWduYXR1cmVLZXkiOiJDL2p3UmJ1MWkzcXluS0FWWTdXN000bVVzQkZIVUZpMm1zM0hBWFJvdXprPSIsImFjY291bnRTaWduYXR1cmUiOiJxVm9ocEFxYlU2N3VxNSswQzg2KzhKMVlTVjRxcjFScUVIczE0YnVxZVV6U1RBRUx0YUozZHpzUVFxS1ZpMHpnK3pvRkUrQXA4ODhpVEtNVWc1Z3FBdz09IiwiZGV2aWNlU2lnbmF0dXJlIjoibWtEekcvYTJUUnc1VkU0aklFUC9HV3ZCSVlLbllxRXA5Y09oODZsNXBiL2RFcy85dTRZc05GTHJJcFJiaUVSLzZTTlJ3RTY0ZFl6TmxUTHhhSjhpQ1E9PSJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiI5NDcwMzUzNjI2OToyOUBzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJRdjQ4RVc3dFl0NnNweWdGV08xdXpPSmxMQVJSMUJZdHByTnh3RjBhTHM1In19XSwicGxhdGZvcm0iOiJhbmRyb2lkIiwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzI5NjIyMzA4LCJteUFwcFN0YXRlS2V5SWQiOiJBQUFBQU4wRiJ9';

const prefix = process.env.PREFIX || '.';
const mycode = process.env.CODE || "254";
const author = process.env.STICKER_AUTHOR || '🍂🖤𝗞𝗜𝗡𝗚 𝗔𝗡𝗝𝗔𝗡𝗔 𝗕𝗕𝗛 💦🥵🍂';
const packname = process.env.PACKNAME || 'keith';
const dev = process.env.DEV || '94760105256';
const DevDreaded = dev.split(",");
const botname = process.env.BOTNAME || 'KEITH-MD';
const mode = process.env.MODE || 'public';
const gcpresence = process.env.GC_PRESENCE || 'false';
const antionce = process.env.ANTIVIEWONCE || 'true';
const sessionName = "session";
const presence = process.env.WA_PRESENCE || 'online';

const antitag = process.env.ANTITAG || 'true';
const antidelete = process.env.ANTIDELETE || 'true';
const autoview = process.env.AUTOVIEW_STATUS || 'true';
const autoread = process.env.AUTOREAD || 'true';
const autobio = process.env.AUTOBIO || 'false';

module.exports = {
  sessionName,
  presence,
  autoview,
  autoread,
  botname,
  autobio,
  mode,
  prefix,
  mycode,
  author,
  packname,
  dev,
  DevDreaded,
  gcpresence,
  antionce,
session,
antitag,
antidelete
};
